import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          cz-shortcut-listen="true"
          className={`${geistSans.variable} antialiased`}
        >
          <div className=" min-h-screen bg-[#fff0f0] flex flex-col ">
            <main className="flex-grow">{children}</main>
          </div>
        </body>
      </html>
  );
}
